services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /code
  redis:
    image: redis:alpine
